### ISSUE TITLE
Brass Armor Errors

### ISSUE THREAD

**Issue by Hexidecimark** [celsiusqc/Create-Addon#1]
Create 0.3.2f
Forge 36.2.4
MC 1.16.5

Create Addon V5

When starting server, I get two errors-
Parsing error loading recipe create_addon:leggings_brass
Parsing error loading recipe create_addon:boots_brass

Error text to follow.

**Comment by Hexidecimark** [comment]
<html>
<body>


[16Nov2021 21:11:41.650] [Worker-Main-14/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe create_addon:leggings_brass
--
457 | com.google.gson.JsonSyntaxException: Unknown item 'create_addon:brass_armor_leggings'
458 | at net.minecraft.item.crafting.ShapedRecipe.func_222129_c(ShapedRecipe.java:262) ~[?:?]
459 | at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_292]
460 | at net.minecraft.item.crafting.ShapedRecipe.func_199798_a(ShapedRecipe.java:261) ~[?:?]
461 | at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:281) ~[?:?]
462 | at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:272) ~[?:?]
463 | at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:141) ~[?:?]
464 | at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:61) ~[?:?]
465 | at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:38) ~[?:?]
466 | at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
467 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_292]
468 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_292]
469 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_292]
470 | at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
471 | at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
472 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_292]
473 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_292]
474 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_292]
475 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_292]
476 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_292]
477 | at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_292]
478 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_292]
479 | at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_292]
480 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_292]
481 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_292]


</body>
</html>

<html>
<body>


[16Nov2021 21:11:41.746] [Worker-Main-14/ERROR] [net.minecraft.item.crafting.RecipeManager/]: Parsing error loading recipe create_addon:boots_brass
--
503 | com.google.gson.JsonSyntaxException: Unknown item 'create_addon:brass_armor_boots'
504 | at net.minecraft.item.crafting.ShapedRecipe.func_222129_c(ShapedRecipe.java:262) ~[?:?]
505 | at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_292]
506 | at net.minecraft.item.crafting.ShapedRecipe.func_199798_a(ShapedRecipe.java:261) ~[?:?]
507 | at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:281) ~[?:?]
508 | at net.minecraft.item.crafting.ShapedRecipe$Serializer.func_199425_a_(ShapedRecipe.java:272) ~[?:?]
509 | at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:141) ~[?:?]
510 | at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:61) ~[?:?]
511 | at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:38) ~[?:?]
512 | at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?]
513 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_292]
514 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_292]
515 | at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_292]
516 | at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?]
517 | at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?]
518 | at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:543) [?:1.8.0_292]
519 | at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:667) [?:1.8.0_292]
520 | at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) [?:1.8.0_292]
521 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488) [?:1.8.0_292]
522 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1609) [?:1.8.0_292]
523 | at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596) [?:1.8.0_292]
524 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_292]
525 | at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_292]
526 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_292]
527 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_292]


</body>
</html>
